name: Build and Publish Docker Image in Dockerhub

on:
  push:
    branches:
      - main 
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/**'
      - 'README.md'

env:
  account: ${{ vars.ACCOUNT }}
  container: ${{ vars.CONTAINER }}
  image: ${{ vars.IMAGE }} 
  account_2: deglanrivas

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ vars.DOCKERHUB_ACCOUNT }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run:
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD || true ;

    - name: Build and push Docker image
      env:
        DOCKERHUB_ACCOUNT: ${{ vars.DOCKERHUB_ACCOUNT }}
        DOCKERHUB_IMAGE: ${{ vars.DOCKERHUB_IMAGE }}
        SHA: ${{ github.sha }}
      run:
        docker build -t $DOCKERHUB_ACCOUNT/$DOCKERHUB_IMAGE:latest . || true ;
        docker push $DOCKERHUB_ACCOUNT/$DOCKERHUB_IMAGE:latest || true ;

        docker build -t $DOCKERHUB_ACCOUNT/$DOCKERHUB_IMAGE:$SHA . || true ;
        docker push $DOCKERHUB_ACCOUNT/$DOCKERHUB_IMAGE:$SHA || true ;
