name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image in Dockerhub"]
    types:
      - completed

env:
  account: ${{ vars.ACCOUNT }}
  container: ${{ vars.CONTAINER }}
  image: ${{ vars.IMAGE }} 
  account_2: deglanrivas

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Executing remote command into EC2 by SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull ${{ env.account }}/${{ env.image }}:latest || true 
            docker stop ${{ env.container }} || true 
            docker run --rm -d -p 8080:80 --name ${{ env.container }} ${{ env.account }}/${{ env.image }}:latest