name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image in Dockerhub"]
    types:
      - completed

env:
  account: ${{ vars.DOCKERHUB_ACCOUNT }}
  container: ${{ vars.CONTAINER_NAME }}
  image: ${{ vars.DOCKERHUB_IMAGE }} 
  port_mapping: ${{ vars.PORT_MAPPING }}
  account_2: deglanrivas

jobs:
  deploy-to-ec2:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest docker image
        run:
          docker pull ${{env.account}}/${{env.image}}:latest || true

      - name: Remove old docker containers
        run:
          docker stop ${{env.container}} || true

      - name: Release newer container using latest dockerhub image
        run:
          docker run -d --rm -p ${{env.port_mapping}} --name ${{env.container}} ${{env.account}}/${{env.image}}:latest 